apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  labels:
    deployment: url-shortener-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: url-shortener-backend
  template:
    metadata:
      labels:
        name: url-shortener-backend
        pod: url-shortener-backend
    spec:
      containers:
      - name: url-shortener-backend
      # The image name will change dynamically
        image: asia.gcr.io/PROJECT_ID/MAJOR_VERSION/IMAGE_NAME:RELEASE_VERSION
        env:
          - name:
            valueFrom: REDIS_IP
              configMapKeyRef:
                name: backend-config
                key: REDIS_IP
          - name:
            valueFrom: POSTGRESQL_IP
              configMapKeyRef:
                name: backend-config
                key: POSTGRESQL_IP
          - name:
            valueFrom: DATABASE_NAME
              configMapKeyRef:
                name: backend-config
                key: DATABASE_NAME
          - name:
            valueFrom: POSTGRESQL_PORT_NUMBER
              configMapKeyRef:
                name: backend-config
                key: POSTGRESQL_PORT_NUMBER
          - name:
            valueFrom: REDIS_PORT_NUMBER
              configMapKeyRef:
                name: backend-config
                key: REDIS_PORT_NUMBER
          - name:
            valueFrom: SERVER_HOST
              configMapKeyRef:
                name: backend-config
                key: SERVER_HOST

          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: sql-username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: sql-password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend
spec:
  selector:
    pod: url-shortener-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080